name: Install Tools & Dependencies
description: Installs Node.js & package dependencies

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      shell: bash
