name: Astro Site Check

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build Astro site
      run: npm run astro check
